name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza 1x por dia
  workflow_dispatch:              # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read, write
      
    steps:
      - uses: actions/checkout@v3

      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}}
          user: TurzimmGit
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Commit and push metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update metrics"
          git push
