name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza 1x por dia
  workflow_dispatch:              # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TurzimmGit
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
